// Copyright 2017 Marios Andreopoulos
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package versiongen

import (
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

const (
	defaultFilename    = "version.go"
	DefaultDirtyString = "+"
	DefaultTimeout     = 15 * time.Second
)

// DirtyString is a string appended to the vgVersion constant if you have
// uncommited changes in your current code. Default is "+".
var DirtyString = DefaultDirtyString

// IgnoreFiles is an array of filenames that versiongen should ignore when
// trying to detect uncommited changes. By default it contains only "version.go"
// which if it is the only file changed doesn't affect the runtime behaviour
// of your software.
var IgnoreFiles = []string{"version.go"}

// Timeout is of type time.Duration and is the amount of time versiongen will
// wait for each git command it runs to complete before killing it. Default
// is 15 * time.Second.
var Timeout = DefaultTimeout

type versionData struct {
	describeTags string
	commit       string
	dirty        bool
}

// Create will create a file named version.go in the directory you ran
// 'go generate', that will contain two constants:
//
// vgVersion: The version of your program as given by 'git describe --tags'
// plus the DirtyString variable if you have uncommited changes.
//
// vgHash: The SHA1 hash of your current commit.
func Create() error {
	return CreateFile(defaultFilename)
}

// CreateFile will work as Create() but instead of writing version.go in the
// directory you ran 'go generate' in, it will write filename instead (which
// may include a path).
func CreateFile(filename string) error {
	// Get version
	version, err := runGitSingleLineReturn("git", "describe", "--tags")
	if err != nil {
		return errors.New("Could not run 'git describe --tags'. " +
			"Are there any tags in your repo? Error: " + err.Error())
	}

	// Get SHA1
	hash, err := runGitSingleLineReturn("git", "rev-parse", "HEAD")
	if err != nil {
		return errors.New("Could not run 'git rev-parse HEAD' " +
			"to get commit hash. Error: " + err.Error())
	}

	// Get uncommited changes, split them by line
	diffIndex, err := runGitSingleLineReturn("git", "diff-index", "HEAD")
	if err != nil {
		errors.New("Could not run 'git diff-index HEAD' " +
			"to detect uncommited changes. Error: " + err.Error())
	}
	var diffIndexLines []string
	if strings.TrimSpace(diffIndex) != "" { // Because direct assignment will give us []string{""}
		diffIndexLines = strings.Split(strings.TrimSpace(diffIndex), "\n")
	}

	uncommitedChanges := false
UNCOMMITED:
	for _, v := range diffIndexLines { // For each uncommited, changed file
		matches := 0
		for _, v2 := range IgnoreFiles { // Check against each of blacklisted files
			if strings.Contains(v, v2) {
				matches++
			}
		}
		if matches == 0 { // If none matched, this file has uncommited changes, build is dirty
			uncommitedChanges = true
			break UNCOMMITED
		}
	}
	if uncommitedChanges {
		version += DirtyString
	}

	log.Println("Setting vgVersion to: " + version)
	log.Println("Setting vgHash to: " + hash)
	log.Printf("Setting vgClean to: %v\n", !uncommitedChanges)

	err = writeVersionFile(filename, versionData{version, hash, uncommitedChanges})
	return err
}

// Run a command and return the results and possible errors.
func runGitSingleLineReturn(command string, args ...string) (string, error) {
	cmd := exec.Command(command, args...)

	timer := time.AfterFunc(Timeout, func() { cmd.Process.Kill() })
	out, err := cmd.CombinedOutput()
	timer.Stop()
	if err != nil {
		return "", err
	}

	result := strings.TrimSpace(string(out))
	return result, nil
}

// Write the version file.
func writeVersionFile(filename string, data versionData) error {
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	out := fmt.Sprintf(`package main
// auto generated by github.com/andmarios/go-versiongen

const (
	vgVersion   = "%s"
	vgHash      = "%s"
	vgClean     = %v
)
`, data.describeTags, data.commit, !data.dirty)

	_, err = file.Write([]byte(out))
	return err
}
